apiVersion: v1
kind: Service
metadata:
  name: realworld-frontend-http
  namespace: realworld
spec:
  selector:
    app: realworld-frontend
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld-frontend
  namespace: realworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworld-frontend
  template:
    metadata:
      name: realworld-frontend
      namespace: realworld
      labels:
        app: realworld-frontend
    spec:
      containers:
        - name: realworld-frontend
          image: hseeberger/realworld-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 25Mi
            limits:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: RUST_LOG
              value: realworld_frontend=debug,tower_http=debug,info
