/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

/// Credentials : Credentials to login an existing user.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Credentials {
    /// Unique email address, used for login.
    #[serde(rename = "email")]
    pub email: String,
    /// Password.
    #[serde(rename = "password")]
    pub password: String,
}

impl Credentials {
    /// Credentials to login an existing user.
    pub fn new(email: String, password: String) -> Credentials {
        Credentials { email, password }
    }
}
