/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Errors {
    #[serde(rename = "body")]
    pub body: Vec<String>,
}

impl Errors {
    pub fn new(body: Vec<String>) -> Errors {
        Errors { body }
    }
}
