/*
 * realworld-backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericErrorBody {
    #[serde(rename = "body")]
    pub body: Vec<String>,
}

impl GenericErrorBody {
    pub fn new(body: Vec<String>) -> GenericErrorBody {
        GenericErrorBody { body }
    }
}
