/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericError {
    #[serde(rename = "errors")]
    pub errors: Box<crate::models::GenericErrorBody>,
}

impl GenericError {
    pub fn new(errors: crate::models::GenericErrorBody) -> GenericError {
        GenericError {
            errors: Box::new(errors),
        }
    }
}
