/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericErrorBody {
    #[serde(rename = "body")]
    pub body: Vec<String>,
}

impl GenericErrorBody {
    pub fn new(body: Vec<String>) -> GenericErrorBody {
        GenericErrorBody { body }
    }
}
