/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

/// LoginRequest : Request to login an existing user.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginRequest {
    #[serde(rename = "user")]
    pub user: Box<crate::models::Credentials>,
}

impl LoginRequest {
    /// Request to login an existing user.
    pub fn new(user: crate::models::Credentials) -> LoginRequest {
        LoginRequest {
            user: Box::new(user),
        }
    }
}
