/*
 * realworld-backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// NewUser : New user to be registered.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewUser {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl NewUser {
    /// New user to be registered.
    pub fn new(username: String, email: String, password: String) -> NewUser {
        NewUser {
            username,
            email,
            password,
        }
    }
}
