/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

/// RegisterUserRequest : Request to register a new user.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterUserRequest {
    #[serde(rename = "user")]
    pub user: Box<crate::models::NewUser>,
}

impl RegisterUserRequest {
    /// Request to register a new user.
    pub fn new(user: crate::models::NewUser) -> RegisterUserRequest {
        RegisterUserRequest {
            user: Box::new(user),
        }
    }
}
