/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnprocessableEntity {
    #[serde(rename = "errors")]
    pub errors: Vec<String>,
}

impl UnprocessableEntity {
    pub fn new(errors: Vec<String>) -> UnprocessableEntity {
        UnprocessableEntity { errors }
    }
}
