/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

/// UpdateUser : Update for the currently logged in user. As `bio` is optional in [User], `None`
/// means deleting the current `bio`.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUser {
    #[serde(
        rename = "bio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bio: Option<Option<String>>,
    /// An email address.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// New type for `secrecy::SecretString`.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl UpdateUser {
    /// Update for the currently logged in user. As `bio` is optional in [User], `None` means
    /// deleting the current `bio`.
    pub fn new() -> UpdateUser {
        UpdateUser {
            bio: None,
            email: None,
            password: None,
            username: None,
        }
    }
}
