/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

/// UpdateUserRequest : Request to update the currently logged in user.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserRequest {
    #[serde(rename = "user")]
    pub user: Box<crate::models::UpdateUser>,
}

impl UpdateUserRequest {
    /// Request to update the currently logged in user.
    pub fn new(user: crate::models::UpdateUser) -> UpdateUserRequest {
        UpdateUserRequest {
            user: Box::new(user),
        }
    }
}
