/*
 * realworld-backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// UserResponse : A user.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResponse {
    #[serde(rename = "user")]
    pub user: Box<crate::models::User>,
}

impl UserResponse {
    /// A user.
    pub fn new(user: crate::models::User) -> UserResponse {
        UserResponse {
            user: Box::new(user),
        }
    }
}
