/*
 * realworld-backend
 *
 * RealWorld backend implementation in Rust.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: git@heikoseeberger.de
 * Generated by: https://openapi-generator.tech
 */

/// UserResponse : A user.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResponse {
    #[serde(rename = "user")]
    pub user: Box<crate::models::User>,
}

impl UserResponse {
    /// A user.
    pub fn new(user: crate::models::User) -> UserResponse {
        UserResponse {
            user: Box::new(user),
        }
    }
}
